services:
  labsec-quarkus:
    build:
      context: ./labsec-quarkus
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_PROFILE=prod
    restart: unless-stopped
    networks:
      - app-network
  labsec-angular:
    build:
      context: ./labsec-angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - labsec-quarkus
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
